

const projectsData = {
    "BUSINESS CONSULTANTA":{
        title:"BUSINESS CONSULTANTA",
        points:[
            "ASISTENȚĂ ÎN LANSAREA AFACERII",
            "ÎNREGISTRAREA COMPANIEI CU REȘEDINȚĂ ÎN IT PARK",
            "ÎNREGISTRAREA ÎN REPUBLICA MOLDOVA A COMPANIILOR DE EXPORT- IMPORT",
            "LEGALIZAREA CETĂŢENILOR STRĂINI PE TERITORIUL REPUBLICII MOLDOVA",
            "CUMPĂRAREA SAU VÂNZAREA COMPANIEI FUZIUNEA SAU ABSORBȚIA COMPANIILOR",
            "ELABORAREA PLANULUI DE AFACERI",
            "PERGATIRE SET DE DOCUMENTE PENTRU PARTICIOPARE IN TENDERE, GRANTURI, PROIECTE..."
        ]
    },
    "SERVICII DE CONTABILITATE":{
        title:"SERVICII DE CONTABILITATE",
        points:[
            "• ASISTENȚĂ ÎN LANSAREA AFACERII",
            "• ÎNREGISTRAREA COMPANIEI CU REȘEDINȚĂ ÎN IT PARK",
            "• ÎNREGISTRAREA ÎN REPUBLICA MOLDOVA A COMPANIILOR DE EXPORT- IMPORT",
            "• LEGALIZAREA CETĂŢENILOR STRĂINI PE TERITORIUL REPUBLICII MOLDOVA",
            "CUMPĂRAREA SAU VÂNZAREA COMPANIEI FUZIUNEA SAU ABSORBȚIA COMPANIILOR",
            "ELABORAREA PLANULUI DE AFACERI",
            "PERGATIRE SET DE DOCUMENTE PENTRU PARTICIOPARE IN TENDERE, GRANTURI, PROIECTE..."
        ]
    },
    "SERVICII MANAGEMENT RESURSE UMANE SI SALARIZARE":{
        title:"SERVICII MANAGEMENT RESURSE UMANE SI SALARIZARE",
        points:[
            "• ASISTENȚĂ ÎN LANSAREA AFACERII",
            "• ÎNREGISTRAREA COMPANIEI CU REȘEDINȚĂ ÎN IT PARK",
            "• ÎNREGISTRAREA ÎN REPUBLICA MOLDOVA A COMPANIILOR DE EXPORT- IMPORT",
            "• LEGALIZAREA CETĂŢENILOR STRĂINI PE TERITORIUL REPUBLICII MOLDOVA",
            "CUMPĂRAREA SAU VÂNZAREA COMPANIEI FUZIUNEA SAU ABSORBȚIA COMPANIILOR",
            "ELABORAREA PLANULUI DE AFACERI",
            "PERGATIRE SET DE DOCUMENTE PENTRU PARTICIOPARE IN TENDERE, GRANTURI, PROIECTE..."
        ]
    },
    "ANALIZA MANAGERIALA":{
        title:"ANALIZA MANAGERIALA",
        points:[
            "• ASISTENȚĂ ÎN LANSAREA AFACERII",
            "• ÎNREGISTRAREA COMPANIEI CU REȘEDINȚĂ ÎN IT PARK",
            "• ÎNREGISTRAREA ÎN REPUBLICA MOLDOVA A COMPANIILOR DE EXPORT- IMPORT",
            "• LEGALIZAREA CETĂŢENILOR STRĂINI PE TERITORIUL REPUBLICII MOLDOVA",
            "CUMPĂRAREA SAU VÂNZAREA COMPANIEI FUZIUNEA SAU ABSORBȚIA COMPANIILOR",
            "ELABORAREA PLANULUI DE AFACERI",
            "PERGATIRE SET DE DOCUMENTE PENTRU PARTICIOPARE IN TENDERE, GRANTURI, PROIECTE..."
        ]
    },
}

export default projectsData